.github/workflows/publish-site.yml
Dockerfile

Create docker image when publishing site #105

add docker

---

src/main/kotlin/org/olafneumann/regex/generator/ui/HtmlView.kt
src/main/kotlin/org/olafneumann/regex/generator/ui/html/ResultDisplayPart.kt

Copy does not work.
Issue Number: #181 
- Copy button works now.

#181 Fix copy button

---

src/main/kotlin/org/olafneumann/regex/generator/output/CodeGenerator.kt
src/test/kotlin/org/olafneumann/regex/generator/output/CodeGeneratorTest.kt

Fix VB.net generator output

---

src/main/kotlin/org/olafneumann/regex/generator/js/JQuery.kt
src/main/kotlin/org/olafneumann/regex/generator/ui/DisplayContract.kt
src/main/kotlin/org/olafneumann/regex/generator/ui/HtmlView.kt
src/main/kotlin/org/olafneumann/regex/generator/ui/UiController.kt
src/main/kotlin/org/olafneumann/regex/generator/ui/html/TimerController.kt
src/main/kotlin/org/olafneumann/regex/generator/ui/html/UserInputDelayer.kt
src/main/resources/index.html

The user input is shortened to 1000 characters if the user input exceeds 1000 characters.An alert will be shown directly under the user input to inform the user what is happening.
Issue Number: #177 
- Limit user input to 1000 characters
- Show warning to user if too many characters are entered.

Add input limit

---

.github/workflows/build-and-publish.yml
.github/workflows/build-and-test.yml

The docker images generated while building the project will contain an additional platform: arm64

Add ARM64 as docker platform

---

src/main/resources/index.html

- added a warning under the generated code that the code is generated and maybe doesn't work.

Insert code warning

---

.gitattributes
Dockerfile
README.md
build.gradle
gradle-wrapper.properties

Currently, docker is only used to deploy, and you build first with local installation. It means the build doesn't necessarily works on docker, and we have to install gradle to develop.
Issue Number: 1
We can now build the server image like before by building the project into docker in a multi staged Dockerfile.
It is both safer and more convenient / flexible.

Docker-build (multi staged)

---

.github/workflows/build-and-publish.yml
.github/workflows/build-and-test.yml

No build arguments are passed to the docker build.
a build argument `APP_ENV=github` will be passed to the docker build.

add build arguments to docker build

---

Dockerfile
README.md

As mentioned in #225 it is more convenient for the users to not provide the build args. The we can add the build argument when building via Github Actions.

default to local docker build #225

---

src/main/kotlin/org/olafneumann/regex/generator/ui/html/UserGuide.kt
src/main/resources/styles/regex-generator.css

Adjust the guide design a little bit.
Issue Number: #18
Closes #18

#18 change guide design

---

src/main/kotlin/org/olafneumann/regex/generator/ui/html/RecognizerDisplayPart.kt

A tooltip is being added to the match presenters.
Issue Number: #250
-
-
-

#250 add tooltip to match presenter

---

src/main/kotlin/org/olafneumann/regex/generator/output/CodeGenerator.kt
src/test/kotlin/org/olafneumann/regex/generator/output/CodeGeneratorTest.kt

Issue Number: #259
The generated Python code was wrong. It was technically working, but not doing what was expected. This behaviour has been changed.
The behaviour of the Python generator has been improved.

Improve Python code generator

---

Dockerfile

Set version number for alpine image in docker file.

Add alpine version

---

.github/workflows/combine-prs.yml
.github/workflows/publish-project.yml

Combine prs branch

---

gradle/wrapper/gradle-wrapper.properties

`gradlew` fails when trying to launch Java classes, which are incompatible with the used JVM.
`gradlew` works as expected.

Update Gradle bundle for the gradlew command

---

src/main/kotlin/org/olafneumann/regex/generator/regex/RecognizerMatch.kt

Wrong match presenter shown.
Issue Number: #277
The old match presenter is discarded in order to create a new one for the new input character.

#277 fix comparison

---

README.md
src/main/kotlin/org/olafneumann/regex/generator/regex/RecognizerRegistry.kt

New pattern added.
Issue Number: #290

#290 add alphanumeric pattern

---

src/main/kotlin/org/olafneumann/regex/generator/RegexGenerator.kt
src/main/kotlin/org/olafneumann/regex/generator/ui/html/LoadingIndicator.kt
src/main/resources/index.html
src/main/resources/styles/regex-generator.css

Add loading animation for slower connections

Add loading animation

---

src/main/kotlin/org/olafneumann/regex/generator/ui/HtmlView.kt
src/main/kotlin/org/olafneumann/regex/generator/ui/parts/P1UserInput.kt

Issue Number: closes #309 
-
-
-

Remove substring

---

.github/workflows/analyze-with-detekt.yml

Issue Number: closes #313
Detekt will now use a newer version to scan the code. It will also use the same configuration as used in the main build process.

Configure Detekt

---

.github/workflows/build-project.yml

Fixes #310
revert workflow for building the project back to ubuntu-latest image.

Revert workflow to run on ubuntu-latest

---

src/main/kotlin/org/olafneumann/regex/generator/recognizer/Recognizer.kt
src/main/kotlin/org/olafneumann/regex/generator/recognizer/RecognizerRegistry.kt
src/main/kotlin/org/olafneumann/regex/generator/recognizer/SimpleRecognizer.kt
src/main/kotlin/org/olafneumann/regex/generator/ui/parts/P2MatchPresenter.kt
src/main/resources/styles/regex-generator.css

Add stripes if only derived recognizers

---

src/main/kotlin/org/olafneumann/regex/generator/RegexGenerator.kt
src/main/kotlin/org/olafneumann/regex/generator/recognizer/RecognizerRegistry.kt
src/main/kotlin/org/olafneumann/regex/generator/regex/PatternCaseModifier.kt
src/main/kotlin/org/olafneumann/regex/generator/regex/RegexCache.kt
src/main/kotlin/org/olafneumann/regex/generator/ui/RGView.kt

minor fixes

---

src/main/kotlin/org/olafneumann/regex/generator/RegexGenerator.kt
src/main/kotlin/org/olafneumann/regex/generator/js/Json.Ext.kt
src/main/kotlin/org/olafneumann/regex/generator/ui/components/Bootstrap.kt
src/main/kotlin/org/olafneumann/regex/generator/ui/components/Injector.kt
src/main/kotlin/org/olafneumann/regex/generator/ui/components/Modal.kt
src/main/resources/styles/regex-generator.css

Add error message for issues

---

src/main/kotlin/org/olafneumann/regex/generator/RegexGenerator.kt
src/main/resources/index.html

Add commit to error message

---

src/main/kotlin/org/olafneumann/regex/generator/ErrorHandler.kt
src/main/kotlin/org/olafneumann/regex/generator/RegexGenerator.kt
src/main/kotlin/org/olafneumann/regex/generator/RegexGeneratorException.kt

Improve error handler

---

src/main/kotlin/org/olafneumann/regex/generator/regex/PatternCaseModifier.kt
src/main/resources/index.html

Disable pattern case modifier

---

src/main/kotlin/org/olafneumann/regex/generator/recognizer/PatternHelper.kt
src/test/kotlin/org/olafneumann/regex/generator/model/PatternRecognizerModelTest.kt
src/test/kotlin/org/olafneumann/regex/generator/regex/RecognizerMatchCombinerTest.kt

Fixes generation of code for closing brackets.
Issue Number: Closes #375

fix brackets

---

src/main/kotlin/org/olafneumann/regex/generator/js/Clarity.kt
src/main/kotlin/org/olafneumann/regex/generator/settings/LocalStorageSettings.kt

Add Clarity consent #381

---

src/main/kotlin/org/olafneumann/regex/generator/settings/ApplicationSettings.kt
src/main/kotlin/org/olafneumann/regex/generator/settings/LocalStorageSettings.kt
src/test/kotlin/org/olafneumann/regex/generator/model/PatternRecognizerModelTest.kt

change persistance

---

src/main/kotlin/org/olafneumann/regex/generator/ui/parts/P2MatchPresenter.kt

Improve indexing #373

---

src/main/kotlin/org/olafneumann/regex/generator/ui/RGController.kt
src/main/kotlin/org/olafneumann/regex/generator/ui/utils/HtmlHelper.kt

fix kotlin warnings

---

.config/detekt.yml
.github/workflows/analyze-with-detekt.yml
.github/workflows/build-project.yml
.github/workflows/test-project.yml
README.md
build.gradle.kts
src/jsMain/kotlin/org/olafneumann/regex/generator/ui/parts/P2MatchPresenter.kt

fix detekt

---

README.md

Commit 926cd1f8ff0d46bdb987209c972df35cbfa6df8b moved the `RecognizerRegistry.java` file. This PR adjusts sources to changes.
Fixed reference

Update `RecognizerRegistry` reference
